# Generated by Django 4.1.1 on 2022-09-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("picture", models.ImageField(upload_to="")),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("living", "Living"), ("deceased", "Deceased")],
                        max_length=15,
                    ),
                ),
                ("nationality", models.JSONField(default=list)),
                (
                    "mortality",
                    models.CharField(
                        choices=[("living", "Living"), ("deceased", "Deceased")],
                        max_length=15,
                    ),
                ),
                ("bio", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Facebook"),
                            (1, "Instagram"),
                            (2, "Twitter"),
                            (3, "Tiktok"),
                            (4, "Snapchat"),
                        ]
                    ),
                ),
                ("link", models.URLField()),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="artists.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=128)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="artists.artist",
                    ),
                ),
            ],
        ),
    ]
