# Generated by Django 4.1.1 on 2022-09-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="movie title")),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(0, "Pending"), (1, "Fulfilled"), (2, "Discarded")]
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
