# Generated by Django 4.1.1 on 2022-09-22 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="request",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="request",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2022, 9, 22, 21, 41, 14, 264900, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.PositiveIntegerField(
                choices=[(0, "Pending"), (1, "Fulfilled"), (2, "Discarded")],
                verbose_name="movie request status",
            ),
        ),
    ]
