# Generated by Django 4.1.1 on 2022-09-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryMovieIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="the category a move belongs to based on it's country of origin",
                        max_length=128,
                    ),
                ),
                (
                    "nickname",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Nollywood"),
                            (1, "Hollywood"),
                            (2, "Tollywood"),
                            (3, "Kollywood"),
                            (4, "Aussiewood"),
                            (5, "Lollywood"),
                            (6, "Bollywood"),
                            (7, "Dhallywood"),
                            (8, "Swahiliwood"),
                            (9, "Riverwood"),
                            (10, "Chinawood"),
                        ]
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Comedy"),
                            (1, "Horror"),
                            (2, "Romance"),
                            (3, "Sciencefiction"),
                            (4, "Action"),
                            (5, "Drama"),
                            (6, "Adventure"),
                            (7, "Thriller"),
                            (9, "Fantasy"),
                            (10, "Western"),
                            (11, "Documentary"),
                            (12, "Animation"),
                            (13, "Crime"),
                            (14, "Romanticcomedy"),
                            (15, "Musical"),
                            (16, "Filmnoir"),
                            (17, "Warfilm"),
                            (18, "Mystery"),
                            (19, "Silent"),
                            (20, "Epic"),
                            (21, "Biopic"),
                            (22, "Sports"),
                            (23, "Disaster"),
                            (24, "Docufiction"),
                        ],
                        help_text="the name of the movie genre",
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "genres",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Comedy"),
                            (1, "Horror"),
                            (2, "Romance"),
                            (3, "Sciencefiction"),
                            (4, "Action"),
                            (5, "Drama"),
                            (6, "Adventure"),
                            (7, "Thriller"),
                            (9, "Fantasy"),
                            (10, "Western"),
                            (11, "Documentary"),
                            (12, "Animation"),
                            (13, "Crime"),
                            (14, "Romanticcomedy"),
                            (15, "Musical"),
                            (16, "Filmnoir"),
                            (17, "Warfilm"),
                            (18, "Mystery"),
                            (19, "Silent"),
                            (20, "Epic"),
                            (21, "Biopic"),
                            (22, "Sports"),
                            (23, "Disaster"),
                            (24, "Docufiction"),
                        ]
                    ),
                ),
                ("release_date", models.DateField()),
                ("synopsis", models.TextField(blank=True)),
                ("cast", models.ManyToManyField(to="artists.artist")),
                (
                    "industry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="movies.countrymovieindustry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "genres",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Comedy"),
                            (1, "Horror"),
                            (2, "Romance"),
                            (3, "Sciencefiction"),
                            (4, "Action"),
                            (5, "Drama"),
                            (6, "Adventure"),
                            (7, "Thriller"),
                            (9, "Fantasy"),
                            (10, "Western"),
                            (11, "Documentary"),
                            (12, "Animation"),
                            (13, "Crime"),
                            (14, "Romanticcomedy"),
                            (15, "Musical"),
                            (16, "Filmnoir"),
                            (17, "Warfilm"),
                            (18, "Mystery"),
                            (19, "Silent"),
                            (20, "Epic"),
                            (21, "Biopic"),
                            (22, "Sports"),
                            (23, "Disaster"),
                            (24, "Docufiction"),
                        ]
                    ),
                ),
                ("release_date", models.DateField()),
                ("synopsis", models.TextField(blank=True)),
                ("cast", models.ManyToManyField(to="artists.artist")),
                (
                    "industry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="movies.countrymovieindustry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "series",
            },
        ),
        migrations.CreateModel(
            name="SeriesVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster", models.ImageField(blank=True, upload_to="")),
                ("file", models.FileField(upload_to="")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("mp4", "Mp4"),
                            ("mkv", "Mkv"),
                            ("avi", "Avi"),
                            ("mov", "Mov"),
                            ("wmv", "Wmv"),
                            ("avchd", "Avchd"),
                            ("flv", "Flv"),
                            ("f4v", "F4V"),
                            ("swf", "Swf"),
                            ("webm", "Webm"),
                            ("mpeg2", "Mpeg2"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="the duration of the video",
                        max_digits=8,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="movies.series",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.PositiveIntegerField(default=1)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.series"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster", models.ImageField(blank=True, upload_to="")),
                ("file", models.FileField(upload_to="")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("mp4", "Mp4"),
                            ("mkv", "Mkv"),
                            ("avi", "Avi"),
                            ("mov", "Mov"),
                            ("wmv", "Wmv"),
                            ("avchd", "Avchd"),
                            ("flv", "Flv"),
                            ("f4v", "F4V"),
                            ("swf", "Swf"),
                            ("webm", "Webm"),
                            ("mpeg2", "Mpeg2"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="the duration of the video",
                        max_digits=8,
                    ),
                ),
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="the episode's number", verbose_name="episode number"
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.season"
                    ),
                ),
            ],
        ),
    ]
