# Generated by Django 4.1.1 on 2022-09-22 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2022, 9, 22, 22, 59, 6, 71990, tzinfo=datetime.timezone.utc
                ),
                help_text="the date and time the movie was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="series",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2022, 9, 22, 22, 59, 14, 237396, tzinfo=datetime.timezone.utc
                ),
                help_text="the date and time the movie was created",
            ),
            preserve_default=False,
        ),
    ]
